#! /usr/bin/env ruby
# require 'pry'
require 'pg'

class CLI
  def initialize(args)
    @args = args
    @app = ExpenseData.new
  end

  def run
    case @args[0]
    when 'list' then @app.list_expenses
    when 'add'
      abort 'You must provide amount and memo.' unless valid_add_input?
      @app.add_expense(@args[1, 2])
    else @app.help
    end
  end

  def valid_add_input?
    !(@args[1] =~ /[^0-9.]/ || @args[2] =~ /[^\w ]/)
  end
end

class ExpenseData
  def initialize
    @db = PG.connect(dbname: 'expenses')
  end

  def list_expenses
    result = @db.exec('SELECT id, created_on, amount, memo FROM expenses;')

    result.each do |tuple|
      columns = [tuple['id'].rjust(4),
                 tuple['created_on'],
                 tuple['amount'].rjust(15),
                 tuple['memo']]
      puts columns.join(' | ')
    end
  end

  def add_expense(args)
    amount, memo = args[0], args[1]
    sql = 'INSERT INTO expenses (amount, memo) VALUES ($1, $2);'

    @db.exec_params(sql, [amount, memo])

    puts "Expense added: #{amount} for #{memo}."
  end

  def help
    puts <<~HEREDOC

              An expense recording system

              Commands:

              add AMOUNT MEMO [DATE] - record a new expense
              clear - delete all expenses
              list - list all expenses
              delete NUMBER - remove expense with id NUMBER
              search QUERY - list expenses with a matching memo field

        HEREDOC
  end
end

CLI.new(ARGV).run
